### ISSUE TITLE
CD and CI

### ISSUE THREAD

**Issue by jkutner** [heroku/buildpack-stdlib#10]
Instead of publishing the stdlib versions from local, I propose that we have CI publish it from well-defined tags.

Each time a new `vX.Y.Z` tag is push (such as `v1.0.0`), the CI server (which will have the S3 creds), runs the tests and uploads a new version corresponding to the tag.

~~Then, we can also define a `latest` tag and point it to the latest release version. CI can either resolve this to a tag, and promote the version, or simply release it as a new version.~~

In this way there is no need to run the `upload.py` locally, avoiding any catastrophes.

**Comment by jkutner** [comment]
I think we should abolish the concept of "latest"

**Comment by kennethreitz** [comment]
We don't publish buildpacks that way, and they're way more sensitive than this. Just a thought. 

 -------------


Buildpacks also have 'latest'. Ideally, all changes will be backwards compatible, so any version bumps won't be destructive for those pointing at it.

**Comment by kennethreitz** [comment]
Also, what CI server would we be using?

**Comment by jkutner** [comment]
We're actually going to move away from publishing buildpacks from local this quarter. But my motivation is largely drawn from not wanting to run the `upload.py` script manually. 

WRT to which CI server, I don't have a preference. I would opt for Travis only because I'm used to it.

**Comment by kennethreitz** [comment]
If Travis can do this, I'm all for it. I've never stored (or trusted) Travis with credentials before, personally.

**Comment by kennethreitz** [comment]
`upload.py` should increment the release number automatically. That'll make it much easier for CI deploys. I'll open an issue for that.

**Comment by kennethreitz** [comment]
`upload.py` is now automatic, and much improved. :sparkles: :cake: :sparkles:

**Comment by kennethreitz** [comment]
Also uses a deployment from heroku now. Very happy with this solution. See the README for details.
