### ISSUE TITLE
use hyphens instead of dashes for function names

### ISSUE THREAD

**Issue by kennethreitz** [heroku/buildpack-stdlib#17]
from @jkutner:

---------------

I've had trouble getting buildpack-stdlib to play well with my buildpack shunit2 tests due to some issues with /bin/sh versus Bash. I've worked through a number of problems, but I've had the most trouble with the hyphens in the function names.

While hyphens work in Bash, they are a nonstandard function-name character and portability between shells is not guaranteed[1].

For example, this script fails:

    #! /bin/sh
    source /dev/stdin <<< "$(curl -s --retry 3 -L https://lang-common.s3.amazonaws.com/buildpack-stdlib/v3/stdlib.sh)"

With the error:

    $ sh test.sh
    /dev/stdin: line 7: `puts-step': not a valid identifier

I know we target Bash 4 on Heroku, but it seems unwise to unnecessarily break other shells.

Before we integrate the stdlib into all of our buildpacks, I vote to change the hyphens to underscores. Does anyone second the motion?

I was able to get things working, but I had to ensure that shunit was going through bash before sourcing any of the stdlib. So we can move forward with hyphens, but it feels like a bad practice.

-Joe

[1] https://unix.stackexchange.com/a/168222

**Comment by kennethreitz** [comment]
I've been using explicitly bash with hypens for 5+ years without any trouble. 

I personally think we should be encouraging our users to be using bash, not sh. Perhaps a better solution is to rename the file `stdlib.bash` instead of `stdlib.sh`?

**Comment by jkutner** [comment]
I agree with encouraging bash, but I think we should avoid restricting to bash only.

Bash is notorious for not really having a spec, but it claims to adhere to [IEEE 1003.1 (“POSIX”)](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html), in which it states that a function name is:

> a word consisting solely of underscores, digits, and alphabetics from the portable character set. The first character of a name is not a digit.

I think hyphens work by shear luck.

**Comment by kennethreitz** [comment]
https://unix.stackexchange.com/questions/168221/are-there-problems-with-hyphens-in-functions-aliases-and-executables

**Comment by kennethreitz** [comment]
Going to change the function names to underscores, for POSIX spec compatibility.

**Comment by kennethreitz** [comment]
#18

**Comment by kennethreitz** [comment]
Deployed in `v4`. 

:sparkles: :cake: :sparkles:
