### ISSUE TITLE
Use a .heroku.com URL

### ISSUE THREAD

**Issue by ojacobson** [heroku/buildpack-stdlib#20]
S3 URLs are crazy long and are kind of opaque. It'd be great if this was

`curl …opts… https://buildpack-stdlib.heroku.com/install`

or something.

**Comment by kennethreitz** [comment]
We'd have to rename the bucket, and current releases are supposed to have permanent URLs. 

I think this would be too difficult to orchestrate.

**Comment by ojacobson** [comment]
Fair enough!
