### ISSUE TITLE
Proposal: puts_verbose

### ISSUE THREAD

**Issue by jmorrell** [heroku/buildpack-stdlib#24]
It would be nice if we could standardize on a way to make the buildpacks log more information for debugging.

Relevant issues in the node buildpack:
https://github.com/heroku/heroku-buildpack-nodejs/issues/190
https://github.com/heroku/heroku-buildpack-nodejs/pull/398

`puts_verbose` would only log its output if an environment variable that we standardize on is set. Suggestion: `$BUILDPACK_VERBOSE`.

And I could also use this same variable to deliberately run `yarn` or `npm` in verbose mode.

Also allows support to have a standard response when builds are failing: run `heroku config:set BUILDPACK_VERBOSE=true` and rebuild.

**Comment by kennethreitz** [comment]
I like this idea.
