### ISSUE TITLE
Add shellcheck to the Travis run

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpack-stdlib#31]
Bash provides the user with many many footguns when writing scripts. One way to try and detect there is shellcheck:
https://github.com/koalaman/shellcheck

I think it would be good to add this to the Travis run.

A random [excerpt](https://github.com/koalaman/shellcheck#testimonials) from shellcheck's README:
> At first you're like "shellcheck is awesome" but then you're like "wtf are we still using bash"
> Alexander Tarasikov, via Twitter

**Comment by kennethreitz** [comment]
Want to send a PR? I'm curious to see the results.

**Comment by edmorley** [comment]
(Fixed by #32 - I forgot to add this issue number to the commit message)
