### ISSUE TITLE
Usage example in readme can cause issues when using multiple buildpacks

### ISSUE THREAD

**Issue by edmorley** [heroku/buildpack-stdlib#38]
The readme suggests using this snippet to ensure the stdlib is cached if used from multiple locations:
```bash
if [[ ! -f  /tmp/stdlib.sh ]]; then
  curl --retry 3 -s https://lang-common.s3.amazonaws.com/buildpack-stdlib/v4/stdlib.sh > /tmp/stdlib.sh
fi
source /tmp/stdlib.sh
```

The problem with this is that if one buildpack pins to one version of the stdlib and another buildpack pins to another, then the second buildpack to run will re-use the cached version from the other buildpack even though it's a different version.

I would recommend adding the version number to the saved local file. ie:
`/tmp/stdlib.sh` -> `/tmp/stdlib-v4.sh`

**Comment by kennethreitz** [comment]
Pull request?

**Comment by kennethreitz** [comment]
fixed

**Comment by edmorley** [comment]
Many thanks :-)
