### ISSUE TITLE
Improve import command and sourcing

### ISSUE THREAD

**Issue by jkutner** [heroku/buildpack-stdlib#5]
Maybe we should recommend this command to import the library:

```bash
source <(curl -s --retry 3 https://lang-common.s3.amazonaws.com/buildpack-stdlib/latest/stdlib.sh)
```

It's a bit more concise and doesn't require a tmp file. It also adds a retry.

**Comment by hunterloftis** [comment]
👍  your bash is more refined than mine @jkutner

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by hunterloftis** [comment]
a quick copy paste into node's buildpack locally gives errors; maybe user error or maybe osx? 1s while I check.

**Comment by kennethreitz** [comment]
thanks for the heads up

**Comment by hunterloftis** [comment]
Looks like bash 3.2 (on my laptop) won't source this, re: http://stackoverflow.com/questions/10520605/bashs-source-command-not-working-with-a-file-curld-from-internet

**Comment by kennethreitz** [comment]
I'm always of the mindset that "explicit is better than implicit", so I think the current way of doing things is fine, especially if it's more compatible with more bashes.

**Comment by kennethreitz** [comment]
Adding a retry is a good idea though

**Comment by hunterloftis** [comment]
The proposed fix works in bash 3.2, and is similar (I really like not having to add another several lines to have an os-independent temp file)

```
source /dev/stdin <<< "$(curl -s --retry 3 https://lang-common.s3.amazonaws.com/buildpack-stdlib/latest/stdlib.sh)"
```

**Comment by kennethreitz** [comment]
Sweet, let's go with that. It's a bit clunky, but it works.

**Comment by hunterloftis** [comment]
What I'm not sure about ^^ is what will happen on error. I suspect perhaps the actual error message will be redirected into source and just give some cryptic syntax error.

**Comment by jkutner** [comment]
I think the README should recommend the way that works in the most places. I can always use a different shorthand in my buildpacks.

**Comment by kennethreitz** [comment]
if S3 responds with XML at all, it will look like this:

```
bash: /dev/stdin: line 1: syntax error near unexpected token `newline'
bash: /dev/stdin: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
```

**Comment by kennethreitz** [comment]
The README has been updated to reflect the new compatible way.

**Comment by hunterloftis** [comment]
@jkutner also my laptop is running really old software. Is the current version of osx running on bash 4? I'm totally fine moving past 3.2 / not holding things up if it's just my local development environment that's ancient.

**Comment by kennethreitz** [comment]
Latest OSX uses GNU bash, version 3.2.57.
