### ISSUE TITLE
we need tests

### ISSUE THREAD

**Issue by hunterloftis** [heroku/buildpack-stdlib#8]
We just merged this into the node buildpack, and once it's stable / working we'll lock onto a specific version. Right now I'm not loving pointing at "latest."

But even once we're pointed at specific versions, we should still have a nice test suite for this thing (at least to test that it won't throw errors and break things - which fortunately it isn't doing).

**Comment by jkutner** [comment]
In addition to unit tests, we need to run integration tests for each buildpack every time a new version of this is published. We can't risk the Java language owner making changes and causing an major outage for Node.js.

**Comment by hunterloftis** [comment]
In node we've set a specific immutable version (2) as the dep instead of
latest. I'd recommend that as a general best practice for any kind of
dependency really.

**Comment by jkutner** [comment]
@hunterloftis Agree

**Comment by kennethreitz** [comment]
done!
