### ISSUE TITLE
Test for the existence of BPLOG_PREFIX and BUILDPACK_LOG_FILE

### ISSUE THREAD

**Issue by jmorrell** [heroku/buildpack-stdlib#9]
https://github.com/heroku/buildpack-stdlib/blob/master/stdlib.sh#L67

This already broke the Ember buildpack when we deployed it, which somehow pointed to `/dev/fd/3`, which didn't exist, though I still don't know how / why. Is there anything we can do to protect against this? My bash-fu is weak.

```
if {{ some condition }}
then
  # execute code depending on $BUILDPACK_LOG_FILE
fi
```

**Comment by kennethreitz** [comment]
what do you think we should do if it doesn't exist? just do nothing?

**Comment by jmorrell** [comment]
If it doesn't exist, aren't we currently doing nothing? Doing nothing vs doing nothing + throwing an error seems like an easy choice.

**Comment by kennethreitz** [comment]
my only hesitancy is that i'd personally rather get an error than just
failing silently. I see no reason why those variables should ever not be
set when using the standard lib.
